name: Tauri Windows Build

on:
  push:
    tags:
      - 'v*.*.*'   # Build on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: npm install

      - name: Install WiX Toolset
        run: choco install wixtoolset -y

      - name: Add WiX to PATH
        run: echo "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        run: npx tauri build

      - name: Upload Windows bundle to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src-tauri/target/release/bundle/windows/*.msi
            src-tauri/target/release/bundle/windows/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
